name: Build and Deploy Microservices

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: ['service1', 'service2', 'service3'] # Define the microservices here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current version of microservice
        id: read-version
        run: |
          VERSION_FILE="./${{ matrix.microservice }}/.version"
          if [ -f "$VERSION_FILE" ]; then
            VERSION=$(cat $VERSION_FILE)
          else
            VERSION="0.0.0"
          fi
          echo "Current version of ${{ matrix.microservice }} is $VERSION"
          echo "microservice_version=$VERSION" >> $GITHUB_ENV

      - name: Determine next release version
        id: next-version
        run: |
          # Increment the patch version
          IFS='.' read -ra VERSION <<< "$microservice_version"
          NEXT_PATCH_VERSION=$(( ${VERSION[2]} + 1 ))
          NEXT_VERSION="${VERSION[0]}.${VERSION[1]}.$NEXT_PATCH_VERSION"
          echo "Next version of ${{ matrix.microservice }} will be $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Build Docker Image for ${{ matrix.microservice }}
        run: |
          docker build -t ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ matrix.microservice }}:$next_version ./${{ matrix.microservice }}
          docker save ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ matrix.microservice }}:$next_version | gzip > ${{ matrix.microservice }}.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOSTNAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.BUILDTOCKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ matrix.microservice }}:$next_version

      - name: Update version file
        run: echo $next_version > ./${{ matrix.microservice }}/.version

      - name: Commit and tag new version
        run: |
          git config --local user.email "github-actions@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./${{ matrix.microservice }}/.version
          git commit -m "Bump ${{ matrix.microservice }} version to $next_version"
          git tag ${{ matrix.microservice }}-v$next_version
          git push --atomic origin main ${{ matrix.microservice }}-v$next_version
