name: Build and Deploy Microservice with Versioning

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: ghcr.io
  IMAGE_NAME: pepper # Change this to your repository name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag is $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine Next Version
        id: next-version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -ra VERSION <<< "${LATEST_TAG#v}"
          NEXT_PATCH_VERSION=$(( ${VERSION[2]} + 1 ))
          NEXT_VERSION="v${VERSION[0]}.${VERSION[1]}.$NEXT_PATCH_VERSION"
          # Check if the next version tag already exists
          while git rev-parse $NEXT_VERSION >/dev/null 2>&1; do
            NEXT_PATCH_VERSION=$(( NEXT_PATCH_VERSION + 1 ))
            NEXT_VERSION="v${VERSION[0]}.${VERSION[1]}.$NEXT_PATCH_VERSION"
          done
          echo "Next version will be $NEXT_VERSION"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOSTNAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Use the secret name you created

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: . # This points to the directory where your Dockerfile is located
          push: true
          tags: |
            ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_VERSION }}
            ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Tag and Push New Version
        run: |
          git config --local user.email "github-actions@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION

      - name: Package Helm Chart
        run: helm package ./helm/my-service

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-release-name ./helm/my-service \
            --set image.repository=${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.NEXT_VERSION }} \
            --namespace my-namespace \
            --create-namespace

      - name: Notify Build Completion
        run: echo "Docker image has been built, pushed, and deployed successfully with version $NEXT_VERSION."
