name: Check Library Versions

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check library versions
        shell: python
        run: |
          import requests

          # Read requirements.txt
          with open("requirements.txt", "r") as f:
              libs = [line.strip() for line in f if not line.startswith("#")]

          base_url = "https://pypi.org/pypi/{}/json"

          # Header for the table
          table = "Library\tUsed Version\tLatest Version\tDescription\n"

          for lib in libs:
              name = lib.split("==")[0]
              used_version = lib.split("==")[1] if "==" in lib else "Not pinned"

              try:
                  response = requests.get(base_url.format(name))
                  data = response.json()

                  latest_version = data["info"]["version"]
                  description = data["info"]["summary"]

                  table += f"{name}\t{used_version}\t{latest_version}\t{description}\n"
              except Exception as e:
                  print(f"Error fetching info for {name}: {e}")

          with open("version_report.txt", "w") as f:
              f.write(table)
