name: Semgrep SAST Scan

on:
  push:
    branches:
      - master

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install semgrep tabulate

    - name: Run Semgrep and get results in JSON
      run: |
        semgrep --config=p/r2c-ci --json -o results.json

    - name: Process Semgrep results
      shell: python
      run: |
        import json
        from tabulate import tabulate

        with open('results.json', 'r') as file:
            results = json.load(file)

        high, medium, low = [], [], []

        for finding in results['results']:
            severity = finding['extra']['severity']
            severity_label = "High" if severity == 'ERROR' else "Medium" if severity == 'WARNING' else "Low"
            row = [severity_label, finding['check_id'], finding['extra']['message']]
            if severity == 'ERROR':
                high.append(row)
            elif severity == 'WARNING':
                medium.append(row)
            else:
                low.append(row)

        all_findings = high + medium + low
        headers = ["Severity", "Check ID", "Message"]
        table = tabulate(all_findings, headers, tablefmt="pipe")
        print(table)
