name: Generate SBOM for Python Project, Display and Upload Tabular Artifact

on:
  push:
    branches:
      - master # Adjust this as needed for your project

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Adjust the Python version as necessary for your project

      # Install system dependencies required for the Python project
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install CycloneDX for SBOM generation
          pip install cyclonedx-bom

      # Generate SBOM
      - name: Generate SBOM
        run: |
          cyclonedx-py -o sbom.xml
          # This generates an SBOM in XML format, you can adjust the output format with the '-f' flag

      # Optional: Display SBOM in tabular format
      # This step assumes you have a script or method to parse the SBOM and display it in a tabular format.
      # - name: Display SBOM in Tabular Format
      #   run: |
      #     python display_sbom_table.py sbom.xml

      # Upload SBOM as an artifact
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: sbom.xml
