on: [push]

jobs:
  python-depcheck:
    runs-on: ubuntu-latest
    name: Python Dependency Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Choose the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Include steps for running tests or other checks
      - name: Run tests/lint
        run: |
          # Replace this with the command to run your tests or linters
          echo "Run your test or lint command here"

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          projectName: 'test'
          scanPath: '.'
          format: 'HTML'
          failBuildOnCVSS: 11 # Only fail the build for very high severity vulnerabilities

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v2
        with:
          name: Dependency Check Report
          path: ./dependency-check-report.html
          # Adjust the above path to where your Dependency Check report is generated.
          # The default path might be different based on the Dependency Check configuration.
