name: Safety Vulnerability Scan and HTML Report

on:
  push:
    branches:
      - master

jobs:
  safety-scan-and-html-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Generate Safety report in JSON
        run: |
          safety check --json > safety_report.json

      - name: Convert Safety JSON to HTML
        run: |
          python - <<EOF
          import json

          with open('safety_report.json') as json_file:
              data = json.load(json_file)
          
          vulnerabilities = data.get('vulnerabilities', [])

          html_output = "<html><head><title>Safety Report</title></head><body>"
          html_output += "<h1>Safety Vulnerability Report</h1>"

          if vulnerabilities:
              html_output += "<table border='1'><tr><th>Package</th><th>Affected</th><th>Installed</th><th>Description</th><th>More Info</th></tr>"
              for vuln in vulnerabilities:
                  html_output += f"<tr><td>{vuln['package']}</td><td>{vuln['vulnerable_spec']}</td><td>{vuln['installed_version']}</td><td>{vuln['description']}</td><td><a href='{vuln['advisory']}'>Advisory</a></td></tr>"
              html_output += "</table>"
          else:
              html_output += "<p>No vulnerabilities found.</p>"

          html_output += "</body></html>"

          with open('safety_report.html', 'w') as html_file:
              html_file.write(html_output)
          EOF

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: safety-html-report
          path: safety_report.html
