name: Generate SBOM for Python Project, Display, Upload Tabular Artifact, and Upload to Dependency-Track

on:
  push:
    branches:
      - master # Adjust this as needed for your project

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Adjust the Python version as necessary for your project

      # Install system dependencies required for the Python project
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies and tabulate library
      - name: Install dependencies and tabulate
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Generate a full list of dependencies including transitive dependencies
      - name: Generate comprehensive requirements.txt
        run: pip freeze > full_requirements.txt

      # Generate Python SBOM using the CycloneDX Action
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./full_requirements.txt
          output: ./bom.json
          format: json

      # Parse the SBOM JSON and create a tabular output
      - name: Parse SBOM and Create Table
        run: |
          python - <<EOF
          import json
          from tabulate import tabulate
          with open('bom.json') as bom_file:
              bom = json.load(bom_file)
              components = bom.get('components', [])
              headers = ['Name', 'Version', 'PURL']
              table_data = [(comp.get('name'), comp.get('version'), comp.get('purl')) for comp in components]
              table = tabulate(table_data, headers, tablefmt='github')
              print(table)
              with open('sbom_table.txt', 'w') as table_file:
                  table_file.write(table)
          EOF

      # Upload the tabular SBOM as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: sbom-tabular-artifact
          path: sbom_table.txt

      # Upload SBOM to Dependency-Track
      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v2.0.0
        with:
          protocol: http # Adjust as needed
          serverHostname: 'your_dependency_track_host' # Change this to your Dependency-Track server hostname
          port: 'your_dependency_track_port' # Change this to your Dependency-Track server port, if not the default HTTPS/HTTP port
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectName: 'Test Project'
          projectVersion: '1.0'
          bomFilename: './bom.json'
          autoCreate: true
