name: Generate SBOM for Python Project and Upload Artifact

on:
  push:
    branches:
      - master # Adjust this as needed for your project

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Adjust the Python version as necessary for your project
      
      # Install system dependencies required for the Python project (like pykerberos)
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
      
      # Install Python dependencies from the requirements.txt file, if present
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Generate Python SBOM using the CycloneDX Action
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./requirements.txt
          output: ./bom.json
          format: json
        
      # Upload the generated SBOM as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: python-sbom-artifact
          path: bom.json
