name: Generate SBOM for Python Project and Upload Artifact


on:
  push:
  workflow_dispatch:

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Adjust the Python version as necessary for your project
          
      # Install dependencies (optional, if your project requires specific packages)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assuming you have a requirements.txt file
      
      # Install CycloneDX for Python
      - name: Install CycloneDX
        run: pip install cyclonedx-bom
      
      # Generate SBOM
      - name: Generate SBOM
        run: cyclonedx-py -o bom.xml
        
      # Upload the generated SBOM as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: python-sbom-artifact
          path: bom.xml
