name: SBOMXML
on:
  push: # Trigger the workflow on push events

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest # Run on the latest Ubuntu version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Check out the current repository

      - name: Set up Python 3.8
        uses: actions/setup-python@v2 # Set up Python environment
        with:
          python-version: '3.8' # Specify the Python version

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev # Install system dependencies

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # Install Python dependencies

      - name: Generate Python SBOM (XML)
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: requirements.txt
          output: bom.xml
          format: xml

      - name: Generate Python SBOM (JSON)
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: requirements.txt
          output: bom.json
          format: json

      - name: Upload XML SBOM to Dependency-Track
        id: upload_xml
        run: |
          PROJECT_UUID="9fc512c7-f293-461b-b07c-19c74d13f00d"
          BOM_FILE="bom.xml"
          BOM_ENCODED=$(base64 -w 0 $BOM_FILE)
          HTTP_RESPONSE=$(curl -k -X "POST" \
            --url "http://164.52.193.50:8081/api/v1/bom" \
            -H "X-Api-Key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"project\":\"$PROJECT_UUID\",\"bom\":\"$BOM_ENCODED\"}" \
            -o response_xml.txt -s -w "%{http_code}")
          if [ "$HTTP_RESPONSE" -ne 200 ]; then
            echo "Failed to upload XML SBOM. HTTP Status: $HTTP_RESPONSE"
            cat response_xml.txt
            exit 1
          fi
          echo "XML SBOM uploaded successfully."
        env:
          DEPENDENCYTRACK_APIKEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}

      - name: Upload JSON SBOM to Dependency-Track
        if: steps.upload_xml.outcome == 'success'
        run: |
          PROJECT_UUID="9fc512c7-f293-461b-b07c-19c74d13f00d"
          BOM_FILE="bom.json"
          BOM_ENCODED=$(base64 -w 0 $BOM_FILE)
          HTTP_RESPONSE=$(curl -k -X "POST" \
            --url "http://164.52.193.50:8081/api/v1/bom" \
            -H "X-Api-Key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"project\":\"$PROJECT_UUID\",\"bom\":\"$BOM_ENCODED\"}" \
            -o response_json.txt -s -w "%{http_code}")
          if [ "$HTTP_RESPONSE" -ne 200 ]; then
            echo "Failed to upload JSON SBOM. HTTP Status: $HTTP_RESPONSE"
            cat response_json.txt
            exit 1
          fi
          echo "JSON SBOM uploaded successfully."
        env:
          DEPENDENCYTRACK_APIKEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}

      - name: Archive SBOM Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifacts
          path: |
            bom.xml
            bom.json
