name: SBOM and Upload to Dependency Track

on:
  push: # Adjust this trigger as needed

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Generate full list of dependencies
      - name: Generate comprehensive requirements.txt
        run: pip freeze > full_requirements.txt

      # Generate Python SBOM
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./full_requirements.txt
          output: ./bom.json
          format: json

      # Upload SBOM to Dependency-Track
      - name: Upload BOM to Dependency-Track
        id: upload_bom
        run: |
          response=$(curl -k -X 'POST' \
            'http://164.52.193.50:8081/api/v1/bom' \
            -H 'X-Api-Key: ${{ secrets.DEPENDENCY_TRACK_APIKEY }}' \
            -H 'Content-Type: multipart/form-data' \
            -F 'projectName=test' \
            -F 'projectVersion=1.0' \
            -F 'autoCreate=true' \
            -F 'bom=@./bom.json' \
            -w "%{http_code}") # This will output the HTTP status code
          echo "response=$response" >> $GITHUB_ENV # This is the new way to set an output

      # Check upload response
      - name: Check Upload Response
        run: |
          if [[ "$response" == "201" ]] || [[ "$response" == "200" ]]; then
            echo "Upload successful"
          else
            echo "Upload response: $response"
            echo "Upload failed"
            exit 1
          fi

      # Parse SBOM and create table
      - name: Parse SBOM and Create Table
        run: |
          python - <<EOF
          import json
          from tabulate import tabulate
          with open('bom.json') as bom_file:
              data = json.load(bom_file)
              components = data.get('components', [])
              table = tabulate(components, headers='keys', tablefmt='github')
              print(table)
              with open('sbom_table.txt', 'w') as f:
                  f.write(table)
          EOF

      # Upload SBOM tabular artifact
      - uses: actions/upload-artifact@v2
        with:
          name: sbom-tabular-artifact
          path: sbom_table.txt
