name: SBOM and Upload to Dependency Track

on:
  push: # Adjust this trigger as needed

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tabulate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Generate full list of dependencies
      - name: Generate comprehensive requirements.txt
        run: pip freeze > full_requirements.txt

      # Generate Python SBOM in JSON format
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./full_requirements.txt
          output: ./bom.json
          format: json

      # Upload SBOM to Dependency-Track
      - name: Upload BOM to Dependency-Track
        id: upload_bom
        run: |
          response=$(curl -X "POST" "http://164.52.193.50:8081/api/v1/bom" \
            -H 'Content-Type: multipart/form-data' \
            -H "X-Api-Key: odt_45JbhGOhjHpZfQ0CC3F5HFF8cVH08zU5" \
            -F "autoCreate=true" \
            -F "projectName=test-aman" \
            -F "projectVersion=1.0" \
            -F "bom=@./bom.json" \
            -w "%{http_code}")
          echo "response=$response" >> $GITHUB_ENV

      # Check upload response
      - name: Check Upload Response
        run: |
          if [[ "$response" == "201" ]] || [[ "$response" == "200" ]]; then
            echo "Upload successful"
          else
            echo "Upload response: $response"
            echo "Upload failed"
            exit 1
          fi

      # Upload SBOM JSON file as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: bom.json
