name: SBOMXML
on:
  push: # Trigger the workflow on push events

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest # Run on the latest Ubuntu version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Check out the current repository

      - name: Set up Python 3.8
        uses: actions/setup-python@v2 # Set up Python environment
        with:
          python-version: '3.8' # Specify the Python version

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev # Install system dependencies

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # Install Python dependencies

      - name: Generate Python SBOM (XML)
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: requirements.txt
          output: bom.xml
          format: xml

      - name: Generate Python SBOM (JSON)
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: requirements.txt
          output: bom.json
          format: json

      - name: Upload XML SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-bom-to-dependency-track@v1.0.0
        with:
          serverhostname: '164.52.193.50:8081'
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectname: 'New Project Name'
          projectversion: '1.0'
          bomfile: 'bom.xml'
          port: 8081

      - name: Upload JSON SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-bom-to-dependency-track@v1.0.0
        with:
          serverhostname: '164.52.193.50:8081'
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectname: 'New Project Name'
          projectversion: '1.0'
          bomfile: 'bom.json'
          port: 8081

      - name: Archive SBOM Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifacts
          path: |
            bom.xml
            bom.json
