name: Secret Scanning

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets && sudo make install
        cd .. && git secrets --scan > git-secrets.json

    - name: Run truffleHog
      run: |
        pip install truffleHog
        truffleHog --json --output truffleHog.json https://github.com/username/reponame.git

    - name: Run secrets
      run: |
        pip install secrets
        secrets ./ > secrets.json

    - name: Upload git-secrets results
      uses: actions/upload-artifact@v2
      with:
        name: git-secrets-results
        path: git-secrets.json

    - name: Upload truffleHog results
      uses: actions/upload-artifact@v2
      with:
        name: truffleHog-results
        path: truffleHog.json

    - name: Upload secrets results
      uses: actions/upload-artifact@v2
      with:
        name: secrets-results
        path: secrets.json
