name: XMLSBOM

on:
  push: # Adjust this trigger as needed

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Generate full list of dependencies
      - name: Generate comprehensive requirements.txt
        run: pip freeze > full_requirements.txt

      # Generate Python SBOM in XML format
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./full_requirements.txt
          output: ./bom.xml
          format: xml

      # Encode SBOM to Base64
      - name: Encode SBOM to Base64
        run: |
          bom=$(base64 -w 0 bom.xml)
          echo "ENCODED_BOM=$bom" >> $GITHUB_ENV

      # Upload SBOM to Dependency-Track
      - name: Upload BOM to Dependency-Track
        run: |
          curl -k -X "PUT" \
            --url "http://164.52.193.50:8080/api/v1/bom" \
            -H 'X-Api-Key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}' \
            -H 'Content-Type: application/json' \
            -d "{\"bom\": \"${{ env.ENCODED_BOM }}\", \"projectName\": \"test\", \"projectVersion\": \"1.0\", \"autoCreate\": true}"
        env:
          DEPENDENCYTRACK_APIKEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
