name: SBOMXML
on:
  push: # Adjust this trigger as needed

jobs:
  sbom-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # Generate Python SBOM in XML format
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: requirements.txt
          output: bom.xml
          format: xml

      # Upload SBOM to Dependency-Track
      - name: Upload BOM to Dependency-Track
        run: |
          BOM_ENCODED=$(base64 -w 0 bom.xml)
          curl -k -X "POST" \
            --url "http://164.52.193.50:8081/api/v1/bom" \
            -H "X-Api-Key: ${{ secrets.DEPENDENCYTRACK_APIKEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"project\":\"9fc512c7-f293-461b-b07c-19c74d13f00d\",\"bom\":\"$BOM_ENCODED\"}"
        env:
          DEPENDENCYTRACK_APIKEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
